// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: mall/api.proto

package mall

import (
	proto "github.com/golang/protobuf/proto"
	base "github.com/kkangxu/himlad-proto/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReqGetProducts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comm *base.BaseReq           `protobuf:"bytes,1,opt,name=comm,proto3" json:"comm,omitempty"`
	Para *ReqGetProducts_ReqPara `protobuf:"bytes,2,opt,name=para,proto3" json:"para,omitempty"`
}

func (x *ReqGetProducts) Reset() {
	*x = ReqGetProducts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetProducts) ProtoMessage() {}

func (x *ReqGetProducts) ProtoReflect() protoreflect.Message {
	mi := &file_mall_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetProducts.ProtoReflect.Descriptor instead.
func (*ReqGetProducts) Descriptor() ([]byte, []int) {
	return file_mall_api_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetProducts) GetComm() *base.BaseReq {
	if x != nil {
		return x.Comm
	}
	return nil
}

func (x *ReqGetProducts) GetPara() *ReqGetProducts_ReqPara {
	if x != nil {
		return x.Para
	}
	return nil
}

type RspGetProducts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *base.BaseRet           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *RspGetProducts_RetData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RspGetProducts) Reset() {
	*x = RspGetProducts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspGetProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGetProducts) ProtoMessage() {}

func (x *RspGetProducts) ProtoReflect() protoreflect.Message {
	mi := &file_mall_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGetProducts.ProtoReflect.Descriptor instead.
func (*RspGetProducts) Descriptor() ([]byte, []int) {
	return file_mall_api_proto_rawDescGZIP(), []int{1}
}

func (x *RspGetProducts) GetResult() *base.BaseRet {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RspGetProducts) GetData() *RspGetProducts_RetData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReqGetProducts_ReqPara struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGetProducts_ReqPara) Reset() {
	*x = ReqGetProducts_ReqPara{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetProducts_ReqPara) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetProducts_ReqPara) ProtoMessage() {}

func (x *ReqGetProducts_ReqPara) ProtoReflect() protoreflect.Message {
	mi := &file_mall_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetProducts_ReqPara.ProtoReflect.Descriptor instead.
func (*ReqGetProducts_ReqPara) Descriptor() ([]byte, []int) {
	return file_mall_api_proto_rawDescGZIP(), []int{0, 0}
}

type RspGetProducts_RetData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *RspGetProducts_RetData) Reset() {
	*x = RspGetProducts_RetData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mall_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspGetProducts_RetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGetProducts_RetData) ProtoMessage() {}

func (x *RspGetProducts_RetData) ProtoReflect() protoreflect.Message {
	mi := &file_mall_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGetProducts_RetData.ProtoReflect.Descriptor instead.
func (*RspGetProducts_RetData) Descriptor() ([]byte, []int) {
	return file_mall_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RspGetProducts_RetData) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_mall_api_proto protoreflect.FileDescriptor

var file_mall_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x61, 0x6c, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x6c, 0x6c, 0x1a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6d, 0x61, 0x6c, 0x6c, 0x2f, 0x6d, 0x61,
	0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x47,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x63, 0x6f,
	0x6d, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x52, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x12, 0x30, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x65,
	0x71, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71,
	0x50, 0x61, 0x72, 0x61, 0x52, 0x04, 0x70, 0x61, 0x72, 0x61, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x50, 0x61, 0x72, 0x61, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x52, 0x73, 0x70, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x2e,
	0x52, 0x73, 0x70, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x52,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x34, 0x0a, 0x07,
	0x52, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x61, 0x6c, 0x6c,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x73, 0x32, 0x43, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x6c, 0x12, 0x3b, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x6c, 0x6c,
	0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x1a,
	0x14, 0x2e, 0x6d, 0x61, 0x6c, 0x6c, 0x2e, 0x52, 0x73, 0x70, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6b, 0x61, 0x6e, 0x67, 0x78, 0x75, 0x2f, 0x68, 0x69,
	0x6d, 0x6c, 0x61, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x6c, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mall_api_proto_rawDescOnce sync.Once
	file_mall_api_proto_rawDescData = file_mall_api_proto_rawDesc
)

func file_mall_api_proto_rawDescGZIP() []byte {
	file_mall_api_proto_rawDescOnce.Do(func() {
		file_mall_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_mall_api_proto_rawDescData)
	})
	return file_mall_api_proto_rawDescData
}

var file_mall_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mall_api_proto_goTypes = []interface{}{
	(*ReqGetProducts)(nil),         // 0: mall.ReqGetProducts
	(*RspGetProducts)(nil),         // 1: mall.RspGetProducts
	(*ReqGetProducts_ReqPara)(nil), // 2: mall.ReqGetProducts.ReqPara
	(*RspGetProducts_RetData)(nil), // 3: mall.RspGetProducts.RetData
	(*base.BaseReq)(nil),           // 4: BaseReq
	(*base.BaseRet)(nil),           // 5: BaseRet
	(*Product)(nil),                // 6: mall.Product
}
var file_mall_api_proto_depIdxs = []int32{
	4, // 0: mall.ReqGetProducts.comm:type_name -> BaseReq
	2, // 1: mall.ReqGetProducts.para:type_name -> mall.ReqGetProducts.ReqPara
	5, // 2: mall.RspGetProducts.result:type_name -> BaseRet
	3, // 3: mall.RspGetProducts.data:type_name -> mall.RspGetProducts.RetData
	6, // 4: mall.RspGetProducts.RetData.products:type_name -> mall.Product
	0, // 5: mall.Mall.GetProducts:input_type -> mall.ReqGetProducts
	1, // 6: mall.Mall.GetProducts:output_type -> mall.RspGetProducts
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mall_api_proto_init() }
func file_mall_api_proto_init() {
	if File_mall_api_proto != nil {
		return
	}
	file_mall_mall_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mall_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetProducts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspGetProducts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetProducts_ReqPara); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mall_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspGetProducts_RetData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mall_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mall_api_proto_goTypes,
		DependencyIndexes: file_mall_api_proto_depIdxs,
		MessageInfos:      file_mall_api_proto_msgTypes,
	}.Build()
	File_mall_api_proto = out.File
	file_mall_api_proto_rawDesc = nil
	file_mall_api_proto_goTypes = nil
	file_mall_api_proto_depIdxs = nil
}
