// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: iam/api.proto

package iam

import (
	proto "github.com/golang/protobuf/proto"
	base "github.com/kkangxu/himlad-proto/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReqGetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comm *base.BaseReq       `protobuf:"bytes,1,opt,name=comm,proto3" json:"comm,omitempty"`
	Para *ReqGetUser_ReqPara `protobuf:"bytes,2,opt,name=para,proto3" json:"para,omitempty"`
}

func (x *ReqGetUser) Reset() {
	*x = ReqGetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUser) ProtoMessage() {}

func (x *ReqGetUser) ProtoReflect() protoreflect.Message {
	mi := &file_iam_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUser.ProtoReflect.Descriptor instead.
func (*ReqGetUser) Descriptor() ([]byte, []int) {
	return file_iam_api_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetUser) GetComm() *base.BaseReq {
	if x != nil {
		return x.Comm
	}
	return nil
}

func (x *ReqGetUser) GetPara() *ReqGetUser_ReqPara {
	if x != nil {
		return x.Para
	}
	return nil
}

type RspGetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *base.BaseRet       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Data   *RspGetUser_RetData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RspGetUser) Reset() {
	*x = RspGetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspGetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGetUser) ProtoMessage() {}

func (x *RspGetUser) ProtoReflect() protoreflect.Message {
	mi := &file_iam_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGetUser.ProtoReflect.Descriptor instead.
func (*RspGetUser) Descriptor() ([]byte, []int) {
	return file_iam_api_proto_rawDescGZIP(), []int{1}
}

func (x *RspGetUser) GetResult() *base.BaseRet {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RspGetUser) GetData() *RspGetUser_RetData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReqGetUser_ReqPara struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ReqGetUser_ReqPara) Reset() {
	*x = ReqGetUser_ReqPara{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetUser_ReqPara) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUser_ReqPara) ProtoMessage() {}

func (x *ReqGetUser_ReqPara) ProtoReflect() protoreflect.Message {
	mi := &file_iam_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUser_ReqPara.ProtoReflect.Descriptor instead.
func (*ReqGetUser_ReqPara) Descriptor() ([]byte, []int) {
	return file_iam_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReqGetUser_ReqPara) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RspGetUser_RetData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RspGetUser_RetData) Reset() {
	*x = RspGetUser_RetData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspGetUser_RetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGetUser_RetData) ProtoMessage() {}

func (x *RspGetUser_RetData) ProtoReflect() protoreflect.Message {
	mi := &file_iam_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGetUser_RetData.ProtoReflect.Descriptor instead.
func (*RspGetUser_RetData) Descriptor() ([]byte, []int) {
	return file_iam_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RspGetUser_RetData) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_iam_api_proto protoreflect.FileDescriptor

var file_iam_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x61, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x69, 0x61, 0x6d, 0x1a, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x69, 0x61, 0x6d, 0x2f, 0x69, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1c, 0x0a, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x63, 0x6f, 0x6d, 0x6d,
	0x12, 0x2b, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x50, 0x61, 0x72, 0x61, 0x52, 0x04, 0x70, 0x61, 0x72, 0x61, 0x1a, 0x25, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x50, 0x61, 0x72, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x0a, 0x52, 0x73, 0x70, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x52, 0x73, 0x70, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x28, 0x0a, 0x07, 0x52, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x69, 0x61,
	0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0x34, 0x0a, 0x03,
	0x49, 0x61, 0x6d, 0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0f,
	0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x1a,
	0x0f, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x52, 0x73, 0x70, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x6b, 0x61, 0x6e, 0x67, 0x78, 0x75, 0x2f, 0x68, 0x69, 0x6d, 0x6c, 0x61, 0x64, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_iam_api_proto_rawDescOnce sync.Once
	file_iam_api_proto_rawDescData = file_iam_api_proto_rawDesc
)

func file_iam_api_proto_rawDescGZIP() []byte {
	file_iam_api_proto_rawDescOnce.Do(func() {
		file_iam_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_iam_api_proto_rawDescData)
	})
	return file_iam_api_proto_rawDescData
}

var file_iam_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_iam_api_proto_goTypes = []interface{}{
	(*ReqGetUser)(nil),         // 0: iam.ReqGetUser
	(*RspGetUser)(nil),         // 1: iam.RspGetUser
	(*ReqGetUser_ReqPara)(nil), // 2: iam.ReqGetUser.ReqPara
	(*RspGetUser_RetData)(nil), // 3: iam.RspGetUser.RetData
	(*base.BaseReq)(nil),       // 4: BaseReq
	(*base.BaseRet)(nil),       // 5: BaseRet
	(*User)(nil),               // 6: iam.User
}
var file_iam_api_proto_depIdxs = []int32{
	4, // 0: iam.ReqGetUser.comm:type_name -> BaseReq
	2, // 1: iam.ReqGetUser.para:type_name -> iam.ReqGetUser.ReqPara
	5, // 2: iam.RspGetUser.result:type_name -> BaseRet
	3, // 3: iam.RspGetUser.data:type_name -> iam.RspGetUser.RetData
	6, // 4: iam.RspGetUser.RetData.user:type_name -> iam.User
	0, // 5: iam.Iam.GetUser:input_type -> iam.ReqGetUser
	1, // 6: iam.Iam.GetUser:output_type -> iam.RspGetUser
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_iam_api_proto_init() }
func file_iam_api_proto_init() {
	if File_iam_api_proto != nil {
		return
	}
	file_iam_iam_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_iam_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspGetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetUser_ReqPara); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspGetUser_RetData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iam_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_api_proto_goTypes,
		DependencyIndexes: file_iam_api_proto_depIdxs,
		MessageInfos:      file_iam_api_proto_msgTypes,
	}.Build()
	File_iam_api_proto = out.File
	file_iam_api_proto_rawDesc = nil
	file_iam_api_proto_goTypes = nil
	file_iam_api_proto_depIdxs = nil
}
