// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: base/base.proto

package base

import (
	fmt "fmt"
	_ "github.com/kkangxu/himlad-proto/code"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
