// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: broker/topic.proto

package broker

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 主题定义
type Topic int32

const (
	Topic_NilTopic Topic = 0
	// 新的Topic定义
	Topic_Iam  Topic = 1
	Topic_Mall Topic = 2
)

// Enum value maps for Topic.
var (
	Topic_name = map[int32]string{
		0: "NilTopic",
		1: "Iam",
		2: "Mall",
	}
	Topic_value = map[string]int32{
		"NilTopic": 0,
		"Iam":      1,
		"Mall":     2,
	}
)

func (x Topic) Enum() *Topic {
	p := new(Topic)
	*p = x
	return p
}

func (x Topic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Topic) Descriptor() protoreflect.EnumDescriptor {
	return file_broker_topic_proto_enumTypes[0].Descriptor()
}

func (Topic) Type() protoreflect.EnumType {
	return &file_broker_topic_proto_enumTypes[0]
}

func (x Topic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Topic.Descriptor instead.
func (Topic) EnumDescriptor() ([]byte, []int) {
	return file_broker_topic_proto_rawDescGZIP(), []int{0}
}

var File_broker_topic_proto protoreflect.FileDescriptor

var file_broker_topic_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x28, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x69, 0x6c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49,
	0x61, 0x6d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x6c, 0x10, 0x02, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x6f, 0x61, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x69, 0x6d, 0x6c, 0x61, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_broker_topic_proto_rawDescOnce sync.Once
	file_broker_topic_proto_rawDescData = file_broker_topic_proto_rawDesc
)

func file_broker_topic_proto_rawDescGZIP() []byte {
	file_broker_topic_proto_rawDescOnce.Do(func() {
		file_broker_topic_proto_rawDescData = protoimpl.X.CompressGZIP(file_broker_topic_proto_rawDescData)
	})
	return file_broker_topic_proto_rawDescData
}

var file_broker_topic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_broker_topic_proto_goTypes = []interface{}{
	(Topic)(0), // 0: Topic
}
var file_broker_topic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_broker_topic_proto_init() }
func file_broker_topic_proto_init() {
	if File_broker_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_broker_topic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broker_topic_proto_goTypes,
		DependencyIndexes: file_broker_topic_proto_depIdxs,
		EnumInfos:         file_broker_topic_proto_enumTypes,
	}.Build()
	File_broker_topic_proto = out.File
	file_broker_topic_proto_rawDesc = nil
	file_broker_topic_proto_goTypes = nil
	file_broker_topic_proto_depIdxs = nil
}
